version: '3'
services:
    postgres:
      container_name: db
      image: postgres:9.6
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=test
    test:
      build: .
      command: /bin/bash -c "../wait-for-it/wait-for-it.sh db:5432 -t 10
                            && psql -h db -d test -U postgres < /go/src/github.com/mvsestito/menu-api/db/schema.sql
                            && export DBCONFIGPATH=/go/src/github.com/mvsestito/menu-api/db_config.toml
                            && go list -f '{{if len .TestGoFiles}}\"go test -v {{.ImportPath}}\"{{end}}' ./... | xargs -L 1 -t sh -c"
      depends_on:
        - postgres
    web:
      build: .
      image: menuapi
      command: /bin/bash -c "../wait-for-it/wait-for-it.sh db:5432 -t 10
                            && psql -h db -d test -U postgres < /go/src/github.com/mvsestito/menu-api/db/schema.sql
                            && export DBCONFIGPATH=/go/src/github.com/mvsestito/menu-api/db_config.toml
                            && /go/bin/mock-driver
                            && /go/bin/menu-api"
      ports:
        - "5000:5000"
      depends_on:
        - postgres
